language: node_js
env:
  - HAPPY_TEST_TIMEOUT=60000
node_js:
  - "5.11.1"
  - "4.4.4"
  # - "4.0"
  # - "0.12"
  # - "0.11"
  # - "0.10"
install: npm install --ignore-scripts
script:
  - npm run lint
  - npm run test
  - npm run test-examples
after_success:
  - npm run coverage_ci
