language: node_js
node_js:
  - "stable"
  - "4.1"
  # - "4.0"
  # - "0.12"
  # - "0.11"
  # - "0.10"
install: npm install --ignore-scripts
script:
  - npm run lint
  - npm run test
  - npm run test-examples
after_success:
  - npm run coverage_ci
